sonar.organization=ngohiroshi
sonar.projectKey=NGOhiroshi_kanagawa-park-viewer

sonar.sources=src
sonar.exclusions=src/**/*.test.ts,src/**/*.test.tsx,src/main.tsx

sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info
